### PR TITLE
Update visual plugin template to support TS strict mode

### PR DESCRIPTION
**Pull request by zBritva**
Fix for issue reported in https://github.com/microsoft/PowerBI-visuals-tools/issues/428

### CODE REVIEW

**Comment by emil-eklund** [comment]
Related issue: https://github.com/microsoft/powerbi-visuals-api/pull/47

**Comment by zBritva** [comment]
@emil-eklund we did opposite changes, we still will have the same issue if merge both PR. `options` is optional in PBI visual API.

So, **in powerbi-visuals-api package the `options` should be optional**

@uve Could you confirm it?

**Comment by emil-eklund** [comment]
@zBritva 
I'd be happy to see either approach get merged as long as we can build using strict! 😄 
(I am currently forced to disable strict in my build-pipelines)

One thing I can see is that these changes would imply that a visual _may_ be initialized without constructor options, which seems wrong to me. 
Without any options passed to the constructor, the visual does not have a element-ref on which it can render.

**Comment by zBritva** [comment]
@emil-eklund agree. But API interface comes from PBI

Ping @uve @AviSander

**Review by uve — APPROVED** [review]

**Pull request merged**
