### PR TITLE
fix for #38: revert optional argument

### PR DESCRIPTION
**Pull request by liprec**
Reverting incorrect optional argument `options` in the template file

### CODE REVIEW

**Comment by liprec** [comment]
@zBritva: are you still in charge for this repro?

**Comment by zBritva** [comment]
@liprec Hello, no. Please, contact with @uve

**Comment by liprec** [comment]
@uve can you take a look at the PR?

**Comment by uve** [comment]
> @uve can you take a look at the PR?

Hello @liprec, please run **npm i** command to update version number in package-lock.json as well.

**Comment by liprec** [comment]
@uve `package-lock.json` is updated.

**Comment by uve** [comment]
thanks, @liprec, we'll include this change into the next release

**Pull request merged**
